<a href="https://colab.research.google.com/github/AbdurRafiq/Numpy-Data-Stucture-Python/blob/master/Numpy_Basic_and_Functions_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [0]:
arr_1 = np.array([1,2,5,4])
arr_1

array([1, 2, 5, 4])

In [0]:
arr_1.ndim

1

In [0]:
arr_2 = np.array([[1,2,5,4],[4,41,47,5]])
arr_2

array([[ 1,  2,  5,  4],
       [ 4, 41, 47,  5]])

In [0]:
npa = np.ones((3,4),  dtype=int)
print(npa)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [0]:
arr_1d = np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [0]:
aa = np.linspace(1,12,4)
aa

array([ 1.        ,  4.66666667,  8.33333333, 12.        ])

In [0]:
ss = arr_1d.reshape(2,6)
ss

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [0]:
multi_arr = np.arange(1,13).reshape(2,6)
multi_arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [0]:
multi_arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [0]:
ss.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [0]:
ss.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [0]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [0]:
arr1 + arr1

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [0]:
np.add(arr1,arr2)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [0]:
arr1- arr2 

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [0]:
np.subtract(arr1,arr2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [0]:
arr1 * arr2 

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [0]:
np.multiply(arr1,arr2)

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [0]:
np.divide(arr1,arr2)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [0]:
arr1.max()

9

In [0]:
arr1.max(axis = 0)


array([7, 8, 9])

In [0]:
arr1.min(axis= 1)

array([1, 4, 7])

In [0]:
arr1.min(axis= 1)

In [0]:
np.sum(arr1)

45

In [0]:
np.sum(arr1,axis=0,dtype=float)

array([12., 15., 18.])

In [0]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [0]:
np.std(arr1)

2.581988897471611

In [0]:
np.mean(arr1,axis=0)

array([4., 5., 6.])

In [0]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [0]:
np.log()