<a href="https://colab.research.google.com/github/AbdurRafiq/Numpy-Data-Stucture-Python/blob/master/Python_Numpy_Concatination.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Array **Concatination**

In [0]:
import numpy as np

In [0]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [0]:
arr2 = np.arange(17,33).reshape(4,4)
print(arr2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [0]:
np.concatenate((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [0]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [0]:
np.concatenate((arr1,arr2),axis = 1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [0]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [0]:
np.split(arr1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [0]:
list1 = np.split(arr1,2)
list1

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [0]:
type(list1)

list

In [0]:
type(list1[0])

numpy.ndarray

In [0]:
np.split(arr1,2,axis = 0)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [0]:
d1 = np.array([4,5,7,8,9,4,7])


In [0]:
np.split(d1, [2,4])

[array([4, 5]), array([7, 8]), array([9, 4, 7])]