<a href="https://colab.research.google.com/github/AbdurRafiq/Numpy-Data-Stucture-Python/blob/master/Random_Sampling_with_Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import random

In [0]:
np.random.random(4)

array([0.49440498, 0.31675102, 0.68602104, 0.03432312])

In [0]:
np.random.random((3,3))

array([[0.61242521, 0.92309544, 0.68925371],
       [0.49115329, 0.52007049, 0.42426305],
       [0.93855585, 0.76505202, 0.66174237]])

In [0]:
# for int value
np.random.randint(1,4)

1

In [0]:
np.random.randint(1,4,(4,4))

array([[1, 1, 1, 3],
       [3, 1, 3, 1],
       [3, 3, 1, 3],
       [1, 1, 2, 3]])

In [0]:
np.random.randint(1,4,(2,4,4))

array([[[3, 1, 2, 2],
        [2, 2, 2, 3],
        [3, 1, 3, 3],
        [3, 2, 1, 3]],

       [[1, 2, 3, 3],
        [2, 3, 2, 3],
        [2, 3, 1, 1],
        [1, 3, 1, 3]]])

In [0]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [0]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [0]:
np.random.seed(10)

In [0]:
np.random.randn(3)

array([ 0.00429143, -0.17460021,  0.43302619])

In [0]:
np.random.randn(3,3)

array([[ 1.20303737, -0.96506567,  1.02827408],
       [ 0.22863013,  0.44513761, -1.13660221],
       [ 0.13513688,  1.484537  , -1.07980489]])

In [0]:
x = [1,2,3,4]

np.random.choice(3)

1

In [0]:
np.random.choice(3)

1

In [0]:
for i in range(20):
    print(np.random.choice(x))

3
4
3
1
4
1
3
1
2
4
3
1
3
4
1
4
2
3
4
4


In [0]:
np.random.permutation(x)

array([3, 4, 2, 1])

In [0]:
np.random.permutation(x)

array([2, 4, 1, 3])